"""Seed data for incident knowledge registry — STAB sprint + major historical fixes."""

from __future__ import annotations

from core.incident_knowledge import IncidentRecord


def _stab(
    stab_id: str,
    title: str,
    *,
    category: str = "runtime",
    subsystem: str = "",
    robot: str = "",
    severity: str = "high",
    modules: list[str],
    root_cause: str,
    fix: str,
    rationale: str = "",
    related: list[str] | None = None,
    lessons: list[str] | None = None,
) -> IncidentRecord:
    inc_id = f"INC-2026-{stab_id}"
    return IncidentRecord(
        incident_id=inc_id,
        title=title,
        category=category,
        subsystem=subsystem,
        robot_affected=robot,
        date_first_observed="2026-06-12",
        date_resolved="2026-06-12",
        lifecycle="closed",
        severity=severity,
        priority="p0" if severity == "critical" else "p1",
        environment="uat",
        frequency="intermittent",
        symptoms=title,
        technical_impact="Phase 1 reliability / feed / lifecycle",
        trading_impact="ATO may not pause/resume correctly; feed outages; orphan processes",
        root_cause=root_cause,
        files_modules=modules,
        fix_implemented=fix,
        fix_rationale=rationale or fix,
        regression_risk="Re-test on UAT mode + feed failover after changes to listed modules",
        validation_performed=[
            "pytest stabilization subset",
            "scripts/stabilization_verify.py",
            "phase1_bot_check",
        ],
        stress_testing=["3-cycle stabilization_verify"],
        validation_cycles=3,
        related_incidents=related or [],
        preventive_measures=lessons or [],
        lessons_learned=lessons or [],
        owner="agent",
        legacy_stab_id=stab_id,
        tags=["stabilization-sprint", "closed"],
    )


def build_seed_incidents() -> list[IncidentRecord]:
    stab: list[IncidentRecord] = [
        _stab(
            "STAB-01",
            "UAT state-file split-brain — ATO pause written to wrong path",
            category="configuration",
            robot="kavach",
            subsystem="algo_control",
            modules=["core/algo_control.py", "core/feed_recovery.py"],
            root_cause="pause_algo() used data/batman_state.json while UAT reads data/uat/batman_state.json",
            fix="default_state_path() → state_path(workspace_root()) mode-aware",
            lessons=["All cross-bot state writes must use state_path() — never hard-code data/"],
            related=["INC-2026-STAB-02"],
        ),
        _stab(
            "STAB-02",
            "KAVACH menu reads wrong pause state in UAT",
            category="robot",
            robot="kavach",
            modules=["kavach-2.0/bat_telegram/bots/kavach2/bot.py"],
            root_cause="_read_algo_pause_reason() used default StateManager path",
            fix="Use state_path(workspace_root())",
            related=["INC-2026-STAB-01"],
        ),
        _stab(
            "STAB-03",
            "Failover state lost on DRISHTI restart",
            category="market_data",
            robot="drishti",
            modules=["core/nifty_ltp_failover.py"],
            root_cause="WS→REST session lock lived only in app.bot_data",
            fix="Persist failover to batman_state.json key nifty_ltp_failover",
        ),
        _stab(
            "STAB-04",
            "WebSocket Previous Close frame treated as fatal error",
            category="market_data",
            robot="drishti",
            severity="critical",
            modules=["core/dhan_ws_tick.py", "core/nifty_ltp_websocket_feed.py"],
            root_cause="Dhan v2 control frame without LTP triggered reconnect loop",
            fix="extract_ltp_from_ws_tick skips non-LTP control frames",
            related=["INC-2026-017"],
        ),
        _stab(
            "STAB-05",
            "WebSocket HTTP 429 reconnect storm",
            category="market_data",
            robot="drishti",
            severity="critical",
            modules=["core/nifty_ltp_websocket_feed.py"],
            root_cause="429 incremented failure counter → false failover",
            fix="429 cooldown; do not increment consecutive_failures",
            related=["INC-2026-STAB-06"],
        ),
        _stab(
            "STAB-06",
            "WS 429 cooldown exceeded stale threshold → false failover",
            category="market_data",
            robot="drishti",
            modules=["core/nifty_ltp_feed.py", "core/nifty_ltp_websocket_feed.py"],
            root_cause="Stale watchdog ignored rate_limit_until during cooldown",
            fix="Skip stale alerts during rate-limit cooldown; refresh last_update_at on 429",
            related=["INC-2026-017", "INC-2026-STAB-05"],
        ),
        _stab(
            "STAB-07",
            "Feed gating used save-age only, not JWT exp",
            category="broker",
            robot="drishti",
            modules=["core/token_store.py", "bat_telegram/bots/drishti/nifty_feed_integration.py"],
            root_cause="is_expired() vs effective JWT expiry mismatch",
            fix="is_effectively_expired() gates feed start",
        ),
        _stab(
            "STAB-08",
            "Startup lock / PID reuse failures",
            category="infrastructure",
            modules=[
                "core/instance_lock.py",
                "core/bot_lifecycle.py",
                "core/bot_supervisor.py",
            ],
            root_cause="Plain PID locks; UAT lock path mismatch",
            fix="Tier 1+2 lifecycle hardening + reconcile",
        ),
        _stab(
            "STAB-09",
            "Auth errors retried and triggered failover",
            category="broker",
            robot="drishti",
            modules=[
                "core/nifty_ltp.py",
                "core/nifty_ltp_feed.py",
                "core/nifty_ltp_websocket_feed.py",
            ],
            root_cause="HTTP 401 treated as connection error",
            fix="is_auth_error() + on_auth_failure — no retry, no failover",
        ),
        _stab(
            "STAB-10",
            "KAVACH cold-start without JWT",
            category="robot",
            robot="kavach",
            modules=["core/token_watch.py", "run_kavach2.py"],
            root_cause="token_watch skipped when broker was None at startup",
            fix="Lazy bootstrap via on_token_ready callback",
        ),
        _stab(
            "STAB-11",
            "Supervisor ignored LTP gate failure",
            category="infrastructure",
            modules=["core/bot_supervisor.py"],
            root_cause="LTP gate logged WARN only during market session",
            fix="Abort Start All when LTP gate fails",
        ),
        _stab(
            "STAB-12",
            "health.json not authoritative for RUNNING",
            category="infrastructure",
            modules=["core/bot_health.py", "core/bot_process_status.py"],
            root_cause="classify_bot() ignored health heartbeat file",
            fix="health_confirms_running() upgrades status; stale heartbeat warnings",
        ),
        _stab(
            "STAB-13",
            "Session REST lock with no same-day WS retry",
            category="market_data",
            robot="drishti",
            modules=["core/nifty_ltp_failover.py", "bat_telegram/bots/drishti/nifty_feed_integration.py"],
            root_cause="session_rest_lock_date blocked WS without retry path",
            fix="try_websocket_retry_after_rest() every 15 min",
        ),
        _stab(
            "STAB-14",
            "Live Price opened parallel one-shot WebSocket",
            category="market_data",
            robot="drishti",
            modules=["bat_telegram/bots/drishti/nifty_feed_integration.py"],
            root_cause="Handler always opened new WS while background feed active",
            fix="Prefer fresh cache when background feed healthy",
        ),
        _stab(
            "STAB-15",
            "Lock timeout without retry on state writes",
            category="runtime",
            modules=["core/process_lock.py", "core/state.py"],
            root_cause="exclusive_file_lock() single attempt under concurrent writes",
            fix="retries=3 with backoff on TimeoutError; state.save mkdir parent",
        ),
    ]

    june25: list[IncidentRecord] = [
        IncidentRecord(
            incident_id="INC-2026-016",
            title="Expired UAT fixture expiry blocks ShadowBroker bootstrap",
            category="broker",
            subsystem="shadow_broker",
            robot_affected="kavach",
            date_first_observed="2026-06-25",
            date_resolved="2026-06-25",
            lifecycle="closed",
            severity="critical",
            priority="p0",
            environment="uat",
            frequency="daily_after_weekly_expiry",
            symptoms="Broker connect failed: No NIFTY PE strike 23500 for expiry 2026-06-23 in instrument master",
            business_impact="KAVACH and SARANSH could not load virtual positions; /register and /positions broken",
            technical_impact="create_broker() raised LookupError during ShadowBroker._reload_positions_from_fixture",
            trading_impact="ATO module did not start; no mock order flow",
            root_cause="uat/deployed_positions/positions.json retained past weekly expiry; instrument master drops expired series",
            contributing_factors=[
                "Fixture captured 2026-06-13 for 23 Jun expiry",
                "No auto-roll on weekly expiry boundary",
            ],
            investigation="logs_uat/.../kavach/errors/all_errors.log 10:46 IST; incident CSV kavach::log_error",
            files_modules=[
                "backtest_engine/shadow/shadow_broker.py",
                "backtest_engine/resolver/instrument_master.py",
                "uat/deployed_positions/positions.json",
            ],
            logs_referenced=[
                "logs_uat/runtime/2026-06/2026-06-25/kavach/errors/all_errors.log",
                "data/analytics/incidents/by_domain/kavach/incidents_20260625.csv",
            ],
            fix_implemented="resolve_fixture_trading_expiry() rolls to nearest valid weekly; ShadowBroker clears virtual ledger on roll",
            fix_rationale="UAT book remains loadable without manual fixture edit every expiry day; stale virtual fills cannot corrupt qty",
            regression_risk="New weekly expiry without strikes in master may still fail — operator should refresh screenshot",
            validation_performed=[
                "ShadowBroker.connect_with_token manual test",
                "scripts/run_uat_e2e_verification.py ALL PASSED",
                "3-cycle ShadowBroker stress connect",
                "pytest test_shadow_resolver",
            ],
            stress_testing=["3-cycle broker connect loop"],
            validation_cycles=3,
            remaining_risks=["Operator fixture still shows 23 Jun label until new screenshot ingested"],
            related_incidents=["INC-2026-019"],
            runtime_incident_ids=["kavach::log_error"],
            preventive_measures=[
                "Refresh Sensibull screenshot after weekly expiry",
                "Run validate_fixture.py after positions.json change",
            ],
            lessons_learned=[
                "UAT fixture expiry must roll or block with clear operator message",
                "Virtual ledger must reset when core book expiry changes",
            ],
            future_recommendations=["Optional Telegram reminder on expiry day if fixture age > 5 days"],
            owner="agent",
            tags=["uat", "shadow-broker", "closed"],
        ),
        IncidentRecord(
            incident_id="INC-2026-017",
            title="Mid-session WebSocket false failover — stale watchdog grace gap",
            category="market_data",
            subsystem="nifty_ltp_feed",
            robot_affected="drishti",
            date_first_observed="2026-06-25",
            date_resolved="2026-06-25",
            lifecycle="closed",
            severity="high",
            priority="p1",
            environment="uat",
            frequency="on_ws_reconnect_after_0930",
            symptoms="WS connected at 10:46:02 then ATO auto-paused nifty_ltp_websocket_failed at 10:46:05 before first tick",
            technical_impact="on_feed_stale → on_websocket_crash → REST fallback + algo pause cascade",
            trading_impact="ATO paused repeatedly with nifty_ltp_feed_stale warnings",
            root_cause="Feed stale watchdog only applied 09:15 startup grace, not grace after mid-session WS reconnect when last_update_at is None",
            contributing_factors=["consumer_max_age_seconds=5", "WS connect-to-first-tick latency"],
            investigation="logs_uat/.../drishti/logs/all.log lines 104602–104605 IST",
            files_modules=[
                "core/nifty_ltp_feed.py",
                "core/nifty_ltp_websocket_feed.py",
                "bat_telegram/bots/drishti/nifty_feed_integration.py",
            ],
            logs_referenced=["logs_uat/runtime/2026-06/2026-06-25/drishti/logs/all.log"],
            fix_implemented="mark_transport_started() + is_within_transport_grace() — 30s grace after WS connect / REST service start",
            fix_rationale="Distinguishes cold reconnect from true feed death",
            regression_risk="Very slow first tick (>30s) could still false-positive — monitor ws_ltp audit log",
            validation_performed=["pytest test_feed_stale_watchdog_ws_transport_grace_after_reconnect"],
            validation_cycles=2,
            related_incidents=["INC-2026-STAB-04", "INC-2026-STAB-06"],
            runtime_incident_ids=[],
            lessons_learned=["Transport-level grace must cover reconnect, not only market open"],
            owner="agent",
            tags=["websocket", "closed"],
        ),
        IncidentRecord(
            incident_id="INC-2026-018",
            title="diagnose_robot.py reads wrong log root in UAT mode",
            category="documentation",
            subsystem="observability",
            robot_affected="drishti",
            date_first_observed="2026-06-25",
            date_resolved="2026-06-25",
            lifecycle="closed",
            severity="medium",
            priority="p2",
            environment="uat",
            symptoms="diagnose_robot reported 0 B all.log while bots were logging to logs_uat/",
            root_cause="Hardcoded logs/runtime path ignored batman_mode log_root",
            files_modules=["scripts/diagnose_robot.py"],
            fix_implemented="Use log_runtime_root(ROOT) from core.batman_mode",
            validation_performed=["diagnose_robot.py kavach shows logs_uat paths and non-zero size"],
            validation_cycles=1,
            lessons_learned=["All agent diagnostic tools must be mode-aware"],
            owner="agent",
            tags=["observability", "closed"],
        ),
        IncidentRecord(
            incident_id="INC-2026-019",
            title="PE managed qty mismatch after partial virtual ledger on expiry roll",
            category="testing",
            subsystem="ato_protection",
            robot_affected="kavach",
            date_first_observed="2026-06-25",
            date_resolved="2026-06-25",
            lifecycle="closed",
            severity="high",
            priority="p1",
            environment="uat",
            symptoms="PE managed qty mismatch — broker=65 managed=130 after ATO auto CE protect",
            root_cause="Stale shadow_order_ledger TRADED BUY PE 65 applied on top of rolled fixture before ledger clear fix",
            files_modules=[
                "backtest_engine/shadow/shadow_broker.py",
                "data/uat/shadow_order_ledger.json",
                "modules/ato_protection.py",
            ],
            fix_implemented="Clear virtual ledger when fixture expiry rolls forward",
            related_incidents=["INC-2026-016"],
            validation_performed=["Post-fix KAVACH start — 4 legs PE netQty -130", "ATO startup scan without PE halt"],
            validation_cycles=2,
            owner="agent",
            tags=["uat", "ato", "closed"],
        ),
        IncidentRecord(
            incident_id="INC-2026-020",
            title="UAT E2E log scan flagged pre-fix errors in same-day tail",
            category="testing",
            subsystem="uat_e2e",
            date_first_observed="2026-06-25",
            date_resolved="2026-06-25",
            lifecycle="closed",
            severity="low",
            priority="p3",
            environment="uat",
            symptoms="uat_log_scan FAIL with morning broker errors after afternoon fix",
            root_cause="step_log_scan used full tail window without scoping to latest bot session",
            files_modules=["scripts/run_uat_e2e_verification.py"],
            fix_implemented="_current_session_lines() scans from last 'Batman mode:' startup marker",
            validation_performed=["run_uat_e2e_verification.py uat_log_scan PASS"],
            validation_cycles=2,
            owner="agent",
            tags=["testing", "closed"],
        ),
        IncidentRecord(
            incident_id="INC-2026-021",
            title="JAGRAN Telegram publish timeout during morning feed incident",
            category="connectivity",
            subsystem="jagran",
            robot_affected="jagran",
            date_first_observed="2026-06-25",
            date_resolved="2026-06-25",
            lifecycle="closed",
            severity="medium",
            priority="p2",
            environment="uat",
            symptoms="publish failed: Timed out at 10:50:54 IST during DRISHTI feed failover spam",
            root_cause="Telegram API timeout while incident alerts flooded chat during WS/REST churn",
            files_modules=["bat_telegram/bots/jagran/"],
            fix_implemented="No code change — transient; feed stabilization + sustained auto-resume reduces alert volume",
            related_incidents=["INC-2026-STAB-04", "INC-2026-022"],
            validation_performed=["JAGRAN logs post-11:15 show no further publish timeouts"],
            validation_cycles=1,
            lessons_learned=["Correlate JAGRAN timeouts with upstream feed incidents before chasing bot bugs"],
            owner="agent",
            tags=["telegram", "closed"],
        ),
        IncidentRecord(
            incident_id="INC-2026-022",
            title="DRISHTI cold-start without JWT + ATO pause/resume churn after false WS failover",
            category="connectivity",
            subsystem="nifty_ltp_feed",
            robot_affected="drishti",
            date_first_observed="2026-06-25",
            date_resolved="2026-06-25",
            lifecycle="closed",
            severity="high",
            priority="p1",
            environment="uat",
            symptoms=(
                "Start All 10:43 without JWT until 10:44:52; false WS failover 10:46:05; "
                "~25 min ATO pause/resume churn on nifty_ltp_feed_stale"
            ),
            root_cause=(
                "Mid-session reconnect lacked transport grace (STAB-06 fix); "
                "on_feed_stale_cleared immediately resumed on brief fresh cache while REST was flaky"
            ),
            files_modules=[
                "core/nifty_ltp_feed.py",
                "core/nifty_ltp_websocket_feed.py",
                "core/feed_recovery.py",
                "bat_telegram/bots/drishti/nifty_feed_integration.py",
            ],
            fix_implemented=(
                "Transport grace on reconnect + AUTO_RESUME_STABLE_SECONDS=45 sustained "
                "can_auto_resume_feed_recovery before auto-resume"
            ),
            related_incidents=["INC-2026-STAB-06", "INC-2026-021"],
            validation_performed=[
                "pytest test_feed_recovery sustained resume",
                "Post-fix session no pause/resume churn in drishti logs",
            ],
            validation_cycles=2,
            lessons_learned=[
                "Never auto-resume ATO on first stale_cleared tick — require sustained trading-ready cache"
            ],
            owner="agent",
            tags=["websocket", "ato", "closed"],
        ),
    ]

    return stab + june25
